version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.8.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - run:
          name: install AngularCLI
          command: sudo npm install -g angular-cli
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: build
          command: ng build
      - run:
          name: deploy
          command: rsync -avz --delete dist/genki-landing/* ec2-user@ec2-65-1-107-237.ap-south-1.compute.amazonaws.com:/var/www/html/

workflows:
  orb-free-workflow:
    jobs:
      - deploy
