version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - run:
          name: install AngularCLI
          command: npm install -g angular-cli
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Build
          command: ng build

workflows:
  orb-free-workflow:
    jobs:
      - deploy
